using System.Diagnostics;
using System.Diagnostics.Metrics;
using System.Threading.Channels;
using MechanicalSympathy.Domain.Entities;
using MechanicalSympathy.Domain.ValueObjects;
using Microsoft.Extensions.Logging;

namespace MechanicalSympathy.Core.Infrastructure.Agents;

/// <summary>
/// Agent responsible for order matching using Single Writer Principle.
/// </summary>
/// <remarks>
/// <para>
/// This agent owns all order book state and performs all matching operations.
/// By implementing the Single Writer Principle, we achieve:
/// </para>
/// <list type="bullet">
/// <item>Zero lock contention on the order book</item>
/// <item>Deterministic matching behavior</item>
/// <item>Natural batching of incoming orders</item>
/// <item>Linear scalability with producer count</item>
/// </list>
/// <para>
/// From Martin Fowler's article: "All writes to shared data or resources should
/// originate from a single dedicated thread."
/// </para>
/// </remarks>
public sealed class OrderMatchingAgent : AgentBase<OrderCommand>
{
    private readonly Dictionary<long, OrderBook> _orderBooks = new();
    private readonly Channel<Trade> _tradeOutput;
    private readonly Meter _meter;
    private readonly Counter<long> _ordersProcessed;
    private readonly Counter<long> _tradesGenerated;
    private readonly Histogram<double> _matchingLatency;
    private long _nextTradeId = 1;

    // Statistics (only written by this agent's thread - no locks needed!)
    private long _totalOrdersProcessed;
    private long _totalTradesExecuted;

    /// <summary>Total orders processed by this agent.</summary>
    public long TotalOrdersProcessed => Volatile.Read(ref _totalOrdersProcessed);

    /// <summary>Total trades executed by this agent.</summary>
    public long TotalTradesExecuted => Volatile.Read(ref _totalTradesExecuted);

    /// <summary>
    /// Creates a new order matching agent.
    /// </summary>
    /// <param name="tradeOutput">Channel to publish executed trades.</param>
    /// <param name="meter">Metrics meter for observability.</param>
    /// <param name="logger">Logger instance.</param>
    /// <param name="capacity">Message queue capacity.</param>
    public OrderMatchingAgent(
        Channel<Trade> tradeOutput,
        Meter meter,
        ILogger<OrderMatchingAgent> logger,
        int capacity = 8192)
        : base(capacity, logger, nameof(OrderMatchingAgent))
    {
        _tradeOutput = tradeOutput;
        _meter = meter;

        // Create metrics instruments
        _ordersProcessed = meter.CreateCounter<long>(
            "trading.orders.processed",
            description: "Total orders processed by matching engine");

        _tradesGenerated = meter.CreateCounter<long>(
            "trading.trades.generated",
            description: "Total trades generated by matching engine");

        _matchingLatency = meter.CreateHistogram<double>(
            "trading.matching.latency.us",
            unit: "us",
            description: "Order matching latency in microseconds");
    }

    /// <summary>
    /// Processes an order command. Runs on the agent's dedicated thread.
    /// </summary>
    protected override async ValueTask ProcessMessageAsync(
        OrderCommand command,
        CancellationToken cancellationToken)
    {
        switch (command)
        {
            case PlaceOrderCommand place:
                await ProcessPlaceOrderAsync(place.Order, cancellationToken);
                break;

            case CancelOrderCommand cancel:
                ProcessCancelOrder(cancel.OrderId, cancel.InstrumentId);
                break;
        }
    }

    private async ValueTask ProcessPlaceOrderAsync(Order order, CancellationToken cancellationToken)
    {
        var sw = Stopwatch.StartNew();

        var orderBook = GetOrCreateOrderBook(order.InstrumentId);

        // Match against opposite side
        var trades = MatchOrder(order, orderBook);

        // Output trades to downstream consumers
        foreach (var trade in trades)
        {
            await _tradeOutput.Writer.WriteAsync(trade, cancellationToken);
            _totalTradesExecuted++;
            _tradesGenerated.Add(1);
        }

        // Add remaining quantity to book if limit order with unfilled quantity
        if (order.Type == OrderType.Limit && order.Quantity > 0)
        {
            orderBook.AddOrder(order);
        }
        else if (order.Quantity <= 0)
        {
            order.Status = OrderStatus.Filled;
        }

        _totalOrdersProcessed++;
        _ordersProcessed.Add(1);

        sw.Stop();
        _matchingLatency.Record(sw.Elapsed.TotalMicroseconds);
    }

    private List<Trade> MatchOrder(Order incomingOrder, OrderBook book)
    {
        var trades = new List<Trade>();
        var oppositeLevels = book.GetOppositeSide(incomingOrder.Side);

        // Sequential iteration through price levels (cache-friendly)
        foreach (var level in oppositeLevels)
        {
            if (incomingOrder.Quantity <= 0) break;

            if (!CanMatch(incomingOrder, level.Price)) break;

            // Get mutable access to orders list for efficient removal
            var orders = level.GetOrdersInternal();
            var ordersToRemove = new List<Order>();

            // Sequential iteration through orders at this price level
            foreach (var restingOrder in orders)
            {
                if (incomingOrder.Quantity <= 0) break;

                var matchQty = Math.Min(incomingOrder.Quantity, restingOrder.Quantity);

                trades.Add(Trade.Create(
                    id: _nextTradeId++,
                    buyOrderId: incomingOrder.Side == Side.Buy ? incomingOrder.Id : restingOrder.Id,
                    sellOrderId: incomingOrder.Side == Side.Sell ? incomingOrder.Id : restingOrder.Id,
                    instrumentId: incomingOrder.InstrumentId,
                    price: restingOrder.Price,  // Resting order price
                    quantity: matchQty
                ));

                incomingOrder.Quantity -= matchQty;
                restingOrder.Quantity -= matchQty;

                if (incomingOrder.Quantity < incomingOrder.OriginalQuantity && incomingOrder.Quantity > 0)
                {
                    incomingOrder.Status = OrderStatus.PartiallyFilled;
                }

                if (restingOrder.Quantity <= 0)
                {
                    restingOrder.Status = OrderStatus.Filled;
                    ordersToRemove.Add(restingOrder);
                }
                else
                {
                    restingOrder.Status = OrderStatus.PartiallyFilled;
                }
            }

            // Remove filled orders
            foreach (var order in ordersToRemove)
            {
                orders.Remove(order);
            }
        }

        // Clean up empty price levels
        book.PruneEmptyLevels();

        return trades;
    }

    private bool CanMatch(Order order, decimal levelPrice)
    {
        // Market orders always match
        if (order.Type == OrderType.Market) return true;

        // Limit orders: buy must be >= ask, sell must be <= bid
        return order.Side == Side.Buy
            ? order.Price >= levelPrice
            : order.Price <= levelPrice;
    }

    private void ProcessCancelOrder(long orderId, long instrumentId)
    {
        if (!_orderBooks.TryGetValue(instrumentId, out var book))
            return;

        // Search both sides for the order
        foreach (var level in book.Bids.Concat(book.Asks))
        {
            var order = level.Orders.FirstOrDefault(o => o.Id == orderId);
            if (order != null)
            {
                level.GetOrdersInternal().Remove(order);
                order.Status = OrderStatus.Cancelled;
                break;
            }
        }

        book.PruneEmptyLevels();
    }

    private OrderBook GetOrCreateOrderBook(long instrumentId)
    {
        if (!_orderBooks.TryGetValue(instrumentId, out var book))
        {
            book = new OrderBook(instrumentId);
            _orderBooks[instrumentId] = book;
        }
        return book;
    }

    /// <summary>
    /// Gets a snapshot of the order book for an instrument.
    /// </summary>
    public OrderBookSnapshot? GetOrderBookSnapshot(long instrumentId)
    {
        if (!_orderBooks.TryGetValue(instrumentId, out var book))
            return null;

        return new OrderBookSnapshot(
            InstrumentId: instrumentId,
            BestBid: book.BestBid,
            BestAsk: book.BestAsk,
            Spread: book.Spread,
            TotalBidOrders: book.TotalBidOrders,
            TotalAskOrders: book.TotalAskOrders
        );
    }
}

/// <summary>Base class for order commands.</summary>
public abstract record OrderCommand;

/// <summary>Command to place a new order.</summary>
public sealed record PlaceOrderCommand(Order Order) : OrderCommand;

/// <summary>Command to cancel an existing order.</summary>
public sealed record CancelOrderCommand(long OrderId, long InstrumentId) : OrderCommand;

/// <summary>Immutable snapshot of order book state.</summary>
public readonly record struct OrderBookSnapshot(
    long InstrumentId,
    decimal? BestBid,
    decimal? BestAsk,
    decimal? Spread,
    int TotalBidOrders,
    int TotalAskOrders
);
